YUI.add("yuidoc-meta", function(Y) {
   Y.YUIDoc = { meta: {
    "classes": [
        "CG.Animation",
        "CG.B2DBridge",
        "CG.B2DCirlce",
        "CG.B2DEntity",
        "CG.B2DLine",
        "CG.B2DPolygon",
        "CG.B2DRectangle",
        "CG.B2DRope",
        "CG.B2DWorld",
        "CG.Bitmap",
        "CG.Bound",
        "CG.Buffer",
        "CG.Button",
        "CG.Delta",
        "CG.Director",
        "CG.Emitter",
        "CG.Entity",
        "CG.Font",
        "CG.Layer",
        "CG.Map",
        "CG.MapArea",
        "CG.MapPoint",
        "CG.MapTileLayer",
        "CG.MapTileProperties",
        "CG.MediaAsset",
        "CG.Menu",
        "CG.Morph",
        "CG.Particle",
        "CG.Point",
        "CG.Rectangle",
        "CG.Screen",
        "CG.Sequence",
        "CG.Sprite",
        "CG.TPImage",
        "CG.TexturePacker",
        "CG.Translate",
        "CG.Vector"
    ],
    "modules": [],
    "allModules": []
} };
});